/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.GameBase;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import sk.upjs.ics.GameBase.Entity.Game;
import sk.upjs.ics.GameBase.Entity.Studio;
import sk.upjs.ics.GameBase.FactoryAndDAO.DaoFactory;
import sk.upjs.ics.GameBase.FactoryAndDAO.GameBaseDAO;
import sk.upjs.ics.GameBase.FactoryAndDAO.StudioDAO;

/**
 *
 * @author Uživateľ
 */
public class AddOrEditStudio extends javax.swing.JDialog {

    private long studioID;

    private List<Game> gameList;
    private List<Game> unusedGameList;

    private final StudioDAO studioDAO = DaoFactory.INSTANCE.getStudioDAO();
    private final GameBaseDAO gameBaseDAO = DaoFactory.INSTANCE.getGameBaseDAO();
    
    private java.awt.Frame parent;

    public AddOrEditStudio(java.awt.Frame parent, long ID) {
        super(parent, true);

        this.studioID = ID;
        txtName.setText(studioDAO.getStudio(ID).getName());  
        
        this.parent = parent;
        
        loadStudioData(ID);
    }

    private void loadStudioData(long ID) {
        inicializeGamesLists(ID);

        btnSearchStudio.setEnabled(false);
        cbxListOfGames.setEnabled(true);
        cbxListOfGames.setModel(new javax.swing.DefaultComboBoxModel<>(unusedGameList.toArray()));
        lstGameList.setListData(gameList.toArray());
    }

    private void inicializeGamesLists(long ID) {
        gameList = studioDAO.getListOfGames(ID);
        unusedGameList = gameBaseDAO.listAllGames();
    }

    /**
     * Creates new form AddOrEditStudio
     *
     * @param parent
     * @param modal
     */
    public AddOrEditStudio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        btnSearchStudio = new javax.swing.JButton();
        lblListOfGames = new javax.swing.JLabel();
        cbxListOfGames = new javax.swing.JComboBox();
        btnAddGame = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGameList = new javax.swing.JList();
        btnOK = new javax.swing.JButton();
        lblWarnStudio = new javax.swing.JLabel();
        lblWarnGame = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnDeleteGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblName.setText("Meno: ");

        btnSearchStudio.setText("Hľadať");
        btnSearchStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudioActionPerformed(evt);
            }
        });

        lblListOfGames.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblListOfGames.setText("Zoznam hier: ");

        cbxListOfGames.setEnabled(false);
        cbxListOfGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxListOfGamesActionPerformed(evt);
            }
        });

        btnAddGame.setText("Pridať hru");
        btnAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGameActionPerformed(evt);
            }
        });

        lstGameList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstGameListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstGameList);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lblWarnStudio.setForeground(new java.awt.Color(204, 0, 0));

        lblWarnGame.setForeground(new java.awt.Color(204, 0, 0));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnDeleteGame.setText("Odobrať hru");
        btnDeleteGame.setEnabled(false);
        btnDeleteGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDeleteGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOK))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblListOfGames)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxListOfGames, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddGame))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchStudio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWarnStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblWarnGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(btnSearchStudio)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWarnStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListOfGames)
                    .addComponent(cbxListOfGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddGame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWarnGame, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnDeleteGame))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstGameListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstGameListMouseClicked
        if (evt.getClickCount() == 1 && lstGameList.getSelectedIndex() != -1) {
            game = (Game) lstGameList.getSelectedValue();
            btnDeleteGame.setEnabled(true);
        }
        if (evt.getClickCount() == 2 && lstGameList.getSelectedIndex() != -1) {
            GameDetailForm gameDetailForm = new GameDetailForm(this.parent, true, (Game) lstGameList.getSelectedValue());
            //netusim co ine tam at amiesto null
        }
    }//GEN-LAST:event_lstGameListMouseClicked
    private Game game;

    private void btnSearchStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudioActionPerformed
        if (txtName.getText() != null && !"".equals(txtName.getText())) {
            if (studioDAO.getStudio(txtName.getText()) == null) {
                Studio studio = new Studio();
                studio.setName(txtName.getText());

                if (JOptionPane.showConfirmDialog(this, "Štúdio " + txtName.getText() + " neexistuje. Chcete ho pridať do zoznamu?", "???", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    studioDAO.addStudio(studio);

                    loadStudioData((int) studio.getID());
                    this.studioID = (int) studio.getID();
                    lblWarnStudio.setForeground(Color.green);
                    lblWarnStudio.setText("Štúdio bolo úspešne pridané");                    
                }
            } else {
                Studio studio = studioDAO.getStudio(txtName.getText());
                loadStudioData((int) studio.getID());
                this.studioID = (int) studio.getID();
            }
        }
    }//GEN-LAST:event_btnSearchStudioActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGameActionPerformed
        Game game = (Game) cbxListOfGames.getSelectedItem();
        if (game == null) {
            lblWarnGame.setText("Vyberte hru");
            return;
        }
        if (studioDAO.checkGame(studioID, game.getID())) {
            lblWarnGame.setForeground(Color.red);
            lblWarnGame.setText("Hra už bola pridaná!!");
            return;
        }

        studioDAO.addGameToStudio(studioID, game.getID());
        loadStudioData(studioID);
        lblWarnGame.setForeground(Color.green);
        lblWarnGame.setText("Hra bola úspešne priradená");
    }//GEN-LAST:event_btnAddGameActionPerformed

    private void cbxListOfGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxListOfGamesActionPerformed
        lblWarnGame.setText("");
        lblWarnStudio.setText("");
    }//GEN-LAST:event_cbxListOfGamesActionPerformed

    private void btnDeleteGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGameActionPerformed
        studioDAO.deleteGameFromStudio(studioID, this.game.getID());
        btnDeleteGame.setEnabled(false);
        loadStudioData(studioID);
    }//GEN-LAST:event_btnDeleteGameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGame;
    private javax.swing.JButton btnDeleteGame;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSearchStudio;
    private javax.swing.JComboBox cbxListOfGames;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListOfGames;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWarnGame;
    private javax.swing.JLabel lblWarnStudio;
    private javax.swing.JList lstGameList;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
